name: rtd
channels:
    - conda-forge
    - defaults
dependencies:
    - python<3.11
    - westpa>=2022.03
    - scikit-learn
    - tqdm
    - sphinx-argparse
    - matplotlib
    - networkx
    - mock
    - pillow
    - sphinx==6.2.1 # sphinx 7 breaks "style"
    - sphinx_rtd_theme
    - pip
    - pip:
        - pylcs
        - ray
        - recommonmark
        - readthedocs-sphinx-ext

